### ISSUE TITLE
changing name

### ISSUE THREAD

**Issue by ayoubelmhamdi** [filNaj/tree-setter#10]
this name or the repo is very confusing, why not change it to some cool name like qwerty or azerty (because we do not need to write many symbol)

**Comment by filNaj** [comment]
I agree with you, I wanted to change the name when I forked the original repo, but I kept it this way because the name was used everywhere in the code so I didn't want to break the code and waste time debugging just to change the name.

**Comment by disrupted** [comment]
personally I find the name to be very cool and fitting considering how it works.

**Comment by filNaj** [comment]
@disrupted Glad to hear that cus it'll stay like this

**Comment by TornaxO7** [comment]
I prefer this name, since this should make it easier to associate this as an extension for `nvim-treesitter`.
