### ISSUE TITLE
code structure is broken when triggering the addition of colons

### ISSUE THREAD

**Issue by Mythos-404** [filNaj/tree-setter#11]
# Example code
```rust
fn main() {
    println!("{}", fib(10))
}

fn fib(n: u64) -> u64 {
    fn iter(next: u64, prev: u64, num: u64) -> u64 {
        match num {
            0 | 1 => next,
            _ => iter(prev, prev + next, num - 1),
        }
    }
    iter(0, 1, n)
}

```

# Context
code structure is broken when triggering the addition of colons
![tree-setter](https://github.com/filNaj/tree-setter/assets/96325829/fa1b98ce-04ed-4ff5-9d1f-8b71b7987c11)

**Comment by filNaj** [comment]
The plugin isn't stable for rust yet. Hopefully it will be soon.

**Comment by Mythos-404** [comment]
I've turned off semicolon completion in the rust language, rust's semicolons were too uncertain
But I'm happy with it in other languages.
