### ISSUE TITLE
In Python, after inserting the equals, deletes the next line

### ISSUE THREAD

**Issue by tlarevo** [filNaj/tree-setter#4]
# Bug preview
[![Sct4a.gif](https://s11.gifyu.com/images/Sct4a.gif)](https://gifyu.com/image/Sct4a)

# Context
I'm using NvChad and my `treesitter` config as follows;
```lua
M.treesitter = {
  ensure_installed = {
    "vim",
    "lua",
    "html",
    "css",
    "javascript",
    "typescript",
    "tsx",
    "c",
    "markdown",
    "markdown_inline",
    "python",
    "svelte",
    "dart",
    "elixir",
    "surface",
    "heex",
  },
  indent = {
    enable = true,
  },
  tree_setter = { enable = true },
}
```

**Comment by laureanray** [comment]
This is also happening for C haven't tried other language yet.

**Comment by filNaj** [comment]
This was happening in all languages. It should now be resolved.

**Comment by tlarevo** [comment]
@filNaj Thanks a lot for the effort put in to the plugin, if time permits can you explain how, how adding `return` fixed the issue. I tried fixing the issue myself and couldn't find out the root cause. I'm noob on lua and neovim plugin dev but I would like to learn and contribute whenever possible.

**Comment by filNaj** [comment]
Adding `return` prevents the code to continue any further and reach the `if statement` at the end of the **setter.lua** file. This `if statement` is used to insert a `;` when the user presses on the `enter` key (and not the space bar) to go to the next line. This is done by calling `vim.api.nvim_buf_set_lines()` function. But in the `if character == ':'` block, we are already calling this same function but with different arguments. So by adding the `return`, we prevent the `vim.api.nvim_buf_set_lines()` to be called twice. 

Hope that helps.

**Comment by tlarevo** [comment]
@filNaj thanks a lot for taking time to explain, it makes sense now, I didn't know that with lua you can return without any value. Thanks a lot explaining the scenario 🙏 ❤️
